services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Abdullrahman
      MYSQL_DATABASE: symfony_test_test
      MYSQL_USER: app
      MYSQL_PASSWORD: Abdullrahman
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -pAbdullrahman"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: Abdullrahman
    ports:
      - "8080:80"
    depends_on:
      - database

volumes:
  database_data:
